### ISSUE TITLE
'float' object has no attribute 'rjust'

### ISSUE THREAD

**Issue by oceb1** [oberhamsi/finance-eink-pi#1]
I get the following Error when running the code (Pi Zero W, 3.7" Display)

`Traceback (most recent call last):
  File "/home/pi/finance-eink-pi/main.py", line 134, in <module>
    image = getImage()
  File "/home/pi/finance-eink-pi/main.py", line 98, in getImage
    data['delta'].rjust(9),
AttributeError: 'float' object has no attribute 'rjust'
`

**Comment by oberhamsi** [comment]
that's odd. it seems `delta` is deliverd by the api as float not string as usual. can you verify this in the api?

maybe simply wrapping it in string works `str(delta['delta']).rjust(9)`

**Comment by oceb1** [comment]
Yes, that did the trick. Thanks!
